// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package source

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_infoEventEnter struct {
	_    structs.HostLayout
	Path [80]uint8
	Now  uint64
}

// loadBpf_info returns the embedded CollectionSpec for bpf_info.
func loadBpf_info() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_infoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_info: %w", err)
	}

	return spec, err
}

// loadBpf_infoObjects loads bpf_info and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_infoObjects
//	*bpf_infoPrograms
//	*bpf_infoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_infoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_info()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_infoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_infoSpecs struct {
	bpf_infoProgramSpecs
	bpf_infoMapSpecs
	bpf_infoVariableSpecs
}

// bpf_infoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_infoProgramSpecs struct {
	KprobeExecvePath    *ebpf.ProgramSpec `ebpf:"kprobe_execve_path"`
	KprobeExit          *ebpf.ProgramSpec `ebpf:"kprobe_exit"`
	KretprobeExecveInfo *ebpf.ProgramSpec `ebpf:"kretprobe_execve_info"`
	KretprobeForkInfo   *ebpf.ProgramSpec `ebpf:"kretprobe_fork_info"`
}

// bpf_infoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_infoMapSpecs struct {
	Curproc    *ebpf.MapSpec `ebpf:"curproc"`
	EventsExit *ebpf.MapSpec `ebpf:"events_exit"`
	EventsFork *ebpf.MapSpec `ebpf:"events_fork"`
	EventsInfo *ebpf.MapSpec `ebpf:"events_info"`
	SeenArgs   *ebpf.MapSpec `ebpf:"seen_args"`
}

// bpf_infoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_infoVariableSpecs struct {
}

// bpf_infoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_infoObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_infoObjects struct {
	bpf_infoPrograms
	bpf_infoMaps
	bpf_infoVariables
}

func (o *bpf_infoObjects) Close() error {
	return _Bpf_infoClose(
		&o.bpf_infoPrograms,
		&o.bpf_infoMaps,
	)
}

// bpf_infoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_infoObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_infoMaps struct {
	Curproc    *ebpf.Map `ebpf:"curproc"`
	EventsExit *ebpf.Map `ebpf:"events_exit"`
	EventsFork *ebpf.Map `ebpf:"events_fork"`
	EventsInfo *ebpf.Map `ebpf:"events_info"`
	SeenArgs   *ebpf.Map `ebpf:"seen_args"`
}

func (m *bpf_infoMaps) Close() error {
	return _Bpf_infoClose(
		m.Curproc,
		m.EventsExit,
		m.EventsFork,
		m.EventsInfo,
		m.SeenArgs,
	)
}

// bpf_infoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_infoObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_infoVariables struct {
}

// bpf_infoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_infoObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_infoPrograms struct {
	KprobeExecvePath    *ebpf.Program `ebpf:"kprobe_execve_path"`
	KprobeExit          *ebpf.Program `ebpf:"kprobe_exit"`
	KretprobeExecveInfo *ebpf.Program `ebpf:"kretprobe_execve_info"`
	KretprobeForkInfo   *ebpf.Program `ebpf:"kretprobe_fork_info"`
}

func (p *bpf_infoPrograms) Close() error {
	return _Bpf_infoClose(
		p.KprobeExecvePath,
		p.KprobeExit,
		p.KretprobeExecveInfo,
		p.KretprobeForkInfo,
	)
}

func _Bpf_infoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_info_x86_bpfel.o
var _Bpf_infoBytes []byte
