// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf_tcp returns the embedded CollectionSpec for bpf_tcp.
func loadBpf_tcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_tcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_tcp: %w", err)
	}

	return spec, err
}

// loadBpf_tcpObjects loads bpf_tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_tcpObjects
//	*bpf_tcpPrograms
//	*bpf_tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_tcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_tcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tcpSpecs struct {
	bpf_tcpProgramSpecs
	bpf_tcpMapSpecs
}

// bpf_tcpSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tcpProgramSpecs struct {
	TraceConnectEntry    *ebpf.ProgramSpec `ebpf:"trace_connect_entry"`
	TraceConnectV4Return *ebpf.ProgramSpec `ebpf:"trace_connect_v4_return"`
}

// bpf_tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tcpMapSpecs struct {
	Currsock   *ebpf.MapSpec `ebpf:"currsock"`
	Curtime    *ebpf.MapSpec `ebpf:"curtime"`
	Ipv4Events *ebpf.MapSpec `ebpf:"ipv4_events"`
}

// bpf_tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tcpObjects struct {
	bpf_tcpPrograms
	bpf_tcpMaps
}

func (o *bpf_tcpObjects) Close() error {
	return _Bpf_tcpClose(
		&o.bpf_tcpPrograms,
		&o.bpf_tcpMaps,
	)
}

// bpf_tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tcpMaps struct {
	Currsock   *ebpf.Map `ebpf:"currsock"`
	Curtime    *ebpf.Map `ebpf:"curtime"`
	Ipv4Events *ebpf.Map `ebpf:"ipv4_events"`
}

func (m *bpf_tcpMaps) Close() error {
	return _Bpf_tcpClose(
		m.Currsock,
		m.Curtime,
		m.Ipv4Events,
	)
}

// bpf_tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tcpPrograms struct {
	TraceConnectEntry    *ebpf.Program `ebpf:"trace_connect_entry"`
	TraceConnectV4Return *ebpf.Program `ebpf:"trace_connect_v4_return"`
}

func (p *bpf_tcpPrograms) Close() error {
	return _Bpf_tcpClose(
		p.TraceConnectEntry,
		p.TraceConnectV4Return,
	)
}

func _Bpf_tcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_tcp_x86_bpfel.o
var _Bpf_tcpBytes []byte
